GET http://localhost:3000/users/

###
GET http://localhost:3000/users/60fdda2898b7355038c79bfd
###


POST http://localhost:3000/users/
Content-Type: application/json

{
    "firstname": "Dylan",
    "lastname": "Dent",
    "email": "June 17, 1989"
}
###
DELETE http://localhost:3000/users/60fed347c5f5c517604ce288
###
PATCH  http://localhost:3000/users/60fddff064ec4a03f087938e
Content-Type: application/json

{
    "firstname":"NewName"
}